### ISSUE TITLE
Better base object controller

### ISSUE THREAD

**Issue by xqliu** [betterlife/psi#78]
It should support

- [ ] Search when type and auto pop up suggestions
- [ ] List view when number of objects less than a configured number.
- [ ] Search box when number of objects larger than a configured number.
- [ ] Should be able to configure which field / or combination of fields is used for the display in the list.

> Written by @xqliu
> Created at 2014-11-09T00:24:03.000+0800
> Link to http://betterlife.atlassian.net/browse/BE-11

**Comment by xqliu** [comment]
This task depends on JBS-4 

> Written by @xqliu
> Created at 2014-11-12T00:34:43.000+0800
